# BEGIN
spring:
  datasource:
    url: jdbc:h2:mem:test  # URL для подключения к H2 базе данных в памяти
    username: sa            # Имя пользователя для подключения к базе данных
    password: 123           # Пароль для подключения к базе данных
  jpa:
    show-sql: true          # Включает отображение SQL-запросов в консоли
    hibernate:
      ddl-auto: update      # Автоматически обновляет схему базы данных при каждом запуске приложения
  output:
    ansi:
      enabled: always       # Включает цветной вывод в консоли
# END
